# Base config file. Always use this first.

timing:
  log_freq: 500
  save_freq: 10000
  eval_freq: 500
    # 5000

train:
  batch_size: 25
  learning_rate: 0.0001
  #0.0001
  l2_reg: 0
  gradient_clip: 10

data:
  name: null    # Need to be overwritten

model:
  name: null    # Need to be overwritten
